- icon: icon-user-md
  title: Computer repair
  description: Computer slow, tune-up computer. Programs update, smartphones and tablets.

- icon: icon-diamond
  title: Electronic sales
  description: TV's ,smartphones, tablets, printers, cameras, scanners, cables, computer, laptops, Apple products.

- icon: icon-flask
  title: Data recovery
  description: We recovery datas from SD, HD, cameras, laptops, PC and etc.

- icon: icon-globe
  title: Website Development
  description: Website and app development, build, deploy, SEO, RIA (Rich Internet Applications)

- icon: icon-medkit
  title: Printers reset
  description: We also reset printers and sell it too.

- icon: icon-feed
  title: Banners etc
  description: Create banners, persosal cards, business cards, labels, Banners and presentation. 